#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
FETCH_SCRIPT="$SCRIPT_DIR/fetch_hagezi_rpz.sh"
VALIDATE_SCRIPT="$SCRIPT_DIR/validate_rpz.sh"

usage() {
  cat <<'EOF'
Usage:
  update_blocklist.sh [--profile PROFILE] [--zone-name NAME] [--output-dir DIR] [--state-dir DIR]
  update_blocklist.sh --source-file PATH [--zone-name NAME] [--output-dir DIR] [--state-dir DIR] [--list-profile NAME]

Defaults:
  profile: light
  zone-name: hagezi.local
  output-dir: ./state/generated
  state-dir: ./state
EOF
}

die() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

profile_to_url() {
  case "$1" in
    light) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/light.txt' ;;
    normal) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/multi.txt' ;;
    pro) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.txt' ;;
    pro.mini) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.mini.txt' ;;
    pro.plus) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.plus.txt' ;;
    pro.plus.mini) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/pro.plus.mini.txt' ;;
    ultimate) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/ultimate.txt' ;;
    ultimate.mini) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/ultimate.mini.txt' ;;
    tif) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/tif.txt' ;;
    tif.medium) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/tif.medium.txt' ;;
    tif.mini) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/tif.mini.txt' ;;
    fake) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/fake.txt' ;;
    popupads) printf '%s\n' 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/rpz/popupads.txt' ;;
    *) die "Unsupported profile: $1" ;;
  esac
}

PROFILE='light'
LIST_PROFILE=''
ZONE_NAME='hagezi.local'
OUTPUT_DIR='./state/generated'
STATE_DIR='./state'
SOURCE_FILE=''

while [ "$#" -gt 0 ]; do
  case "$1" in
    --profile)
      [ "$#" -ge 2 ] || die 'Missing value for --profile'
      PROFILE=$2
      shift 2
      ;;
    --list-profile)
      [ "$#" -ge 2 ] || die 'Missing value for --list-profile'
      LIST_PROFILE=$2
      shift 2
      ;;
    --zone-name)
      [ "$#" -ge 2 ] || die 'Missing value for --zone-name'
      ZONE_NAME=$2
      shift 2
      ;;
    --output-dir)
      [ "$#" -ge 2 ] || die 'Missing value for --output-dir'
      OUTPUT_DIR=$2
      shift 2
      ;;
    --state-dir)
      [ "$#" -ge 2 ] || die 'Missing value for --state-dir'
      STATE_DIR=$2
      shift 2
      ;;
    --source-file)
      [ "$#" -ge 2 ] || die 'Missing value for --source-file'
      SOURCE_FILE=$2
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

if [ -n "$SOURCE_FILE" ] && [ -z "$LIST_PROFILE" ]; then
  LIST_PROFILE=$PROFILE
fi

if [ -z "$LIST_PROFILE" ]; then
  LIST_PROFILE=$PROFILE
fi

mkdir -p "$OUTPUT_DIR" "$STATE_DIR"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT INT TERM

DOWNLOADED_ZONE="$TMP_DIR/hagezi-rpz.zone"
GENERATED_CONF="$TMP_DIR/hagezi-rpz.conf"
GENERATED_META="$TMP_DIR/last-update.env"

if [ -n "$SOURCE_FILE" ]; then
  "$FETCH_SCRIPT" --source-file "$SOURCE_FILE" --output "$DOWNLOADED_ZONE"
  SOURCE_URL=$(profile_to_url "$LIST_PROFILE")
else
  "$FETCH_SCRIPT" --profile "$PROFILE" --output "$DOWNLOADED_ZONE"
  SOURCE_URL=$(profile_to_url "$PROFILE")
fi

"$VALIDATE_SCRIPT" "$DOWNLOADED_ZONE" >/dev/null

DOWNLOADED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
ZONE_SHA256=$(sha256sum "$DOWNLOADED_ZONE" | cut -d' ' -f1)

cat > "$GENERATED_CONF" <<EOF
# Generated by update_blocklist.sh on $DOWNLOADED_AT
# Add this file to your unbound configuration manually.
# If you prefer script-only updates, remove the url: line after the first successful sync.
# If your existing config already sets module-config, merge respip into that value instead of overwriting it.

server:
    module-config: "respip validator iterator"

rpz:
    name: "$ZONE_NAME"
    zonefile: "$OUTPUT_DIR/hagezi-rpz.zone"
    url: "$SOURCE_URL"
    for-downstream: no
EOF

cat > "$GENERATED_META" <<EOF
DOWNLOADED_AT=$DOWNLOADED_AT
LIST_PROFILE=$LIST_PROFILE
ZONE_NAME=$ZONE_NAME
SOURCE_URL=$SOURCE_URL
ZONE_SHA256=$ZONE_SHA256
EOF

mv "$DOWNLOADED_ZONE" "$OUTPUT_DIR/hagezi-rpz.zone"
mv "$GENERATED_CONF" "$OUTPUT_DIR/hagezi-rpz.conf"
mv "$GENERATED_META" "$STATE_DIR/last-update.env"

printf 'Updated blocklist in %s\n' "$OUTPUT_DIR"
